sudo: required
language: python
dist: xenial
cache: pip
python:
- '3.6'
- '3.7'
install:
- pip install --upgrade pip
- pip install flake8==3.7.7
- pip install pytest
- pip install coverage codecov
script:
- flake8 texar/ examples/
- coverage run -m pytest
after_success:
- codecov

