sudo: required
language: python
dist: xenial
cache: pip
python:
  - '3.8'
install:
  - travis_wait pip install --upgrade pip
  - travis_wait pip install coverage codecov
  - travis_wait pip install pipenv
script:
  - pipenv install && pipenv shell
  - npm install
  - coverage run -m unittest
  - coverage report 
  - coverage html
after_success:
  - codecov

