language: python
python:
  - 3.5
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install ".[test]" . # install package + test dependencies
script: juego_test.py # run tests
after_success:
  - codecov
