sudo: required
language: python
dist: xenial
cache: pip
python:
  - '3.8'
install:
  - pip install --upgrade pip
  - pip install flake8==3.7.7
  - pip install pytest
  - pip install coverage codecov
  - pip install pipenv
script:
  - pipenv install && pipenv shell
  - npm install
  - flake8 texar/ examples/
  - coverage run -m unittest
  - coverage report 
  - coverage html
after_success:
  - codecov
notifications:
  email:
    - sacchipriscila@gmail.com

